Repository FIRSTPLATO/bus, pull requests merged in 2021-10, with the labels that each got.

#1 Frontend
  docs/info.md
  pro/about.php
  pro/front.php
  pro/index.php
  pro/info.md
Labels: enhancement, hacktoberfest-accepted, ui/ux, major

#3 Hasil scan
  pro/hasil-scan.php
Labels: enhancement, hacktoberfest-accepted, ui/ux, major

#4 upload bukti
  pro/upload-bukti.php
Labels: documentation, enhancement, hacktoberfest-accepted, ui/ux, major

#5 forecasting series
  pro/forecasting.php
Labels: enhancement, hacktoberfest-accepted, major

#6 lunas script
  pro/lunas.php
Labels: enhancement, hacktoberfest-accepted, major

#7 proses upload bukti
  pro/proses-upload-bukti.php
Labels: enhancement, hacktoberfest-accepted, major

#8 bus script
  pro/bus.php
Labels: enhancement, hacktoberfest-accepted, major

#9 proses pesan
  pro/proses-pesan.php
Labels: enhancement, hacktoberfest-accepted, major
